# Generated by Django 2.0 on 2018-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicien',
            name='groupes',
        ),
        migrations.RemoveField(
            model_name='groupemusicien',
            name='groupe',
        ),
        migrations.AddField(
            model_name='groupemusicien',
            name='groupe',
            field=models.ManyToManyField(blank=True, related_name='musiciens_groupe', to='musica.Groupe', verbose_name='grops'),
        ),
        migrations.RemoveField(
            model_name='groupemusicien',
            name='musicien',
        ),
        migrations.AddField(
            model_name='groupemusicien',
            name='musicien',
            field=models.ManyToManyField(blank=True, related_name='groupes_musicien', to='musica.Musicien', verbose_name='musicians'),
        ),
    ]
