# Generated by Django 2.0 on 2018-04-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20180407_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupemusicien',
            name='groupe',
        ),
        migrations.AddField(
            model_name='groupemusicien',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='musiciens_groupe', to='musica.Groupe', verbose_name='grop'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='groupemusicien',
            name='musicien',
        ),
        migrations.AddField(
            model_name='groupemusicien',
            name='musicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupes_musicien', to='musica.Musicien', verbose_name='musician'),
            preserve_default=False,
        ),
    ]
