# Generated by Django 2.0 on 2018-04-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_auto_20180407_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanson',
            name='groupes',
        ),
        migrations.RemoveField(
            model_name='chanson',
            name='musiciens',
        ),
        migrations.AlterField(
            model_name='groupechanson',
            name='chanson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chansons_groupe', to='musica.Chanson', verbose_name='cançon'),
        ),
        migrations.AlterField(
            model_name='groupechanson',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_chanson', to='musica.Groupe', verbose_name='grop'),
        ),
        migrations.AlterField(
            model_name='musicienchanson',
            name='chanson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chansons_musicien', to='musica.Chanson', verbose_name='cançon'),
        ),
        migrations.AlterField(
            model_name='musicienchanson',
            name='musicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musiciens_chanson', to='musica.Musicien', verbose_name='musician'),
        ),
    ]
