# Generated by Django 2.0 on 2018-04-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_auto_20180407_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanson',
            name='image',
        ),
    ]
