# Generated by Django 2.0 on 2018-04-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_remove_chanson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanson',
            name='danse',
            field=models.ManyToManyField(blank=True, related_name='danses_chanson', to='musica.Danse', verbose_name='dança(s)'),
        ),
        migrations.AlterField(
            model_name='chanson',
            name='langues',
            field=models.ManyToManyField(blank=True, related_name='langues_chanson', to='musica.Langue', verbose_name='lenga(s)'),
        ),
        migrations.AlterField(
            model_name='disque',
            name='musiciens',
            field=models.ManyToManyField(blank=True, null=True, related_name='disques_musicien', to='musica.Musicien', verbose_name='musicians'),
        ),
        migrations.AlterField(
            model_name='groupechanson',
            name='chanson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_chanson', to='musica.Chanson', verbose_name='cançon'),
        ),
        migrations.AlterField(
            model_name='groupechanson',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chansons_groupe', to='musica.Groupe', verbose_name='grop'),
        ),
        migrations.AlterField(
            model_name='musicienchanson',
            name='chanson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musiciens_chanson', to='musica.Chanson', verbose_name='cançon'),
        ),
        migrations.AlterField(
            model_name='musicienchanson',
            name='musicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chansons_musicien', to='musica.Musicien', verbose_name='musician'),
        ),
    ]
