# Generated by Django 2.0 on 2018-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_auto_20180407_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disque',
            name='groupes',
            field=models.ManyToManyField(related_name='disques_groupe', to='musica.Groupe', verbose_name='grop(s)'),
        ),
    ]
